name: Build and Tests

on:  
  push:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore Klient/Klient.sln

      - name: Build Solution
        run: |
          msbuild.exe Klient/Klient.sln /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run Tests
        run: vstest.console.exe .\UnitTest\bin\Release\UnitTest.dll



#Run vstest.console.exe .\tests\Sandbox.Tests\bin\Release\Sandbox.Tests.dll
#The test source file "D:\a\STI2022\STI2022\.\tests\Sandbox.Tests\bin\Release\Sandbox.Tests.dll" provided was not found.
