name: php

on:
  push:
    branches: [ serverPushTest ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.5'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php Server/vendor/bin/phpunit  serverTest.php
###############################################################################################
    - name: 🔎 Check IP
      run: curl https://api.ipify.org

    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: klokanek.endora.cz
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: 21
        exclude: |
          **/DSP/**
          **/Klient/**
          **/Server/**
          README.md
          historie_meny.txt
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
          serverTest.php
